### ISSUE TITLE
can't make it work on opensuse

### ISSUE THREAD

**Issue by Macribit** [aoleg94/playkey-linux-monkeypatch#1]
Hi thanks for the program great idea.
Can't make it work though, how should I launch a game? launching the python app should launch the app? or should I launch a game from the browser?
Launching from the browser says couldn't find app to open address playkey://dsaflsjkajdjfsak.whatever.

**Comment by aoleg94** [comment]
User script is obsolete, so you can either adapt it to new Playkey site, or you can use (more reliable) instructions from pastebin (see README.md)
